import {NextResponse} from 'next/server';

async function askGemini(prompt:string){
 const key=process.env.GEMINI_API_KEY; if(!key) return null;
 const model=process.env.GEMINI_MODEL||'gemini-2.5-flash';
 const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${key}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.1,responseMimeType:'application/json'}})});
 if(!res.ok) throw new Error(`Gemini API error ${res.status}`); const d=await res.json(); const t=d.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||'').join('')||'{}'; return JSON.parse(t.replace(/^```json\s*/,'').replace(/\s*```$/,''));
}
function heuristic(questions:any[],answers:any[]){return {mappings:questions.map(q=>{const exact=answers.find(a=>String(a.label).toLowerCase().replace(/\s/g,'')===String(q.label).toLowerCase().replace(/\s/g,'')); const loose=exact||answers.find(a=>String(a.text||'').toLowerCase().includes(String(q.label).toLowerCase())); const aid=loose?.id||null; return {questionId:q.id,answerId:aid,confidence:aid?0.92:0,reason:aid?'The student answer label matches the question label.':'No answer with a matching question label was detected.',marks:aid?Math.min(Number(q.marks)||0,Number(q.marks)||0):0,feedback:aid?'Answer located and ready for teacher review.':'No corresponding answer region was found.'};})};}
export async function POST(req:Request){try{const {questions,answers}=await req.json(); const prompt=`Map student answers to questions for a teacher review UI. Return JSON only {"mappings":[{"questionId":"q1","answerId":"a1 or null","confidence":0-1,"reason":"short explanation","marks":number,"feedback":"concise grading feedback"}]}. Match by explicit labels first, then content/sequence. Never map an answer to two questions unless the same physical answer clearly contains multiple labelled subparts. For unanswered questions use null. Marks must never exceed the question's marks. Questions: ${JSON.stringify(questions)} Answers: ${JSON.stringify(answers)}`; const ai=await askGemini(prompt); return NextResponse.json(ai||heuristic(questions,answers));}catch(e:any){return NextResponse.json({error:e?.message||'Mapping failed.'},{status:500});}}
